name: Test Variables

on:
  workflow_dispatch

env:
  # Use docker.io for Docker Hub if empty
  # REGISTRY: ghcr.io
  REGISTRY: hub.docker.com
  # github.repository as <account>/<repo>
  # IMAGE_NAME: ${{ github.repository }} # 预定义的GitHub环境变量，表示当前GitHub仓库的所有者和仓库名称的组合。
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.event.repository.default_branch }}

jobs:
  test-variables:
    runs-on: ubuntu-latest

    steps:
    - name: Output GitHub context
      run: |
        echo "GitHub Repository [ ${{ toJson( github.repository ) }} ]:" ${{ github.repository }}
        echo "GitHub Repository Owner [ ${{ toJson( github.repository_owner ) }} ]:" ${{ github.repository_owner }}
        echo "GitHub Event Repository Name [${{ github.event.repository.name }}']:" ${{ github.event.repository.name }}
        echo "GitHub Event Repository Default Branch [${{ toJson( github.event.repository.default_branch ) }} ]:" ${{ github.event.repository.default_branch }}
        echo "IMAGE_NAME [ ${{ toJson( env.IMAGE_NAME ) }} ]:" ${{ env.IMAGE_NAME }}
        echo "REGISTRY [ ${{ toJson( env.REGISTRY ) }} ]:" ${{ env.REGISTRY }}
        echo "images [ ${{ toJson( env.REGISTRY }}/${{ env.IMAGE_NAME ) }} ]:" ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        echo "tags [ ${{ toJson( steps.meta.outputs.tags ) }} ]:" ${{ steps.meta.outputs.tags }}
        echo "labels [ ${{ toJson( steps.meta.outputs.labels ) }} ]:" ${{ steps.meta.outputs.labels }}
        echo "TAGS [${{ env.IMAGE_NAME ) }} ]:" ${{ env.IMAGE_NAME }}
        echo "DIGEST [ ${{ toJson( steps.build-and-push.outputs.digest ) }} ]:" ${{ steps.build-and-push.outputs.digest }}

